# Generated by Django 3.0.6 on 2020-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
