# Generated by Django 3.0.6 on 2020-05-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200515_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
