# Generated by Django 3.0.6 on 2020-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price_at',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
