# Generated by Django 3.0.6 on 2020-08-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
        ('portfolio', '0006_transaction_price_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='simulation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Simulation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='simulation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Simulation'),
        ),
    ]
