# Generated by Django 3.0.6 on 2020-08-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
        ('portfolio', '0007_auto_20200829_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='simulation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Simulation'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='simulation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.Simulation'),
        ),
    ]
