# Generated by Django 3.0.6 on 2020-08-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200830_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
