# Generated by Django 3.0.6 on 2020-05-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exchange_time', models.TimeField(blank=True, null=True)),
                ('p_open', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p_low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p_high', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p_close', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
        ),
    ]
