# Generated by Django 3.0.6 on 2020-05-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
