# Generated by Django 3.0.6 on 2020-05-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20200508_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='p_close',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='p_high',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='p_low',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='price',
            name='p_open',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
