# Generated by Django 3.0.6 on 2020-05-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20200508_2312'),
        ('stocks', '0005_auto_20200508_2353'),
    ]

    operations = [
    ]
