# Generated by Django 3.0.6 on 2020-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_merge_20200515_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='interval',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
