# Generated by Django 3.0.6 on 2020-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_price_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(max_length=4),
        ),
    ]
