# Generated by Django 3.0.6 on 2020-05-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20200515_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='creator',
        ),
    ]
