# Generated by Django 3.0.6 on 2020-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_remove_stock_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('1min', '1min'), ('15min', '15min'), ('30min', '30min'), ('60min', '60min'), ('1d', '1d'), ('quote', 'quote')], max_length=5),
        ),
    ]
