# Generated by Django 3.0.6 on 2020-05-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_auto_20200527_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.Stock')),
                ('company_name', models.TextField(max_length=50)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, max_length=50, null=True)),
                ('sector', models.TextField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('ceo', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
