# Generated by Django 3.0.6 on 2020-06-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='p_adjusted_close',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
