# Generated by Django 3.0.6 on 2020-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_price_p_adjusted_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('quote', 'quote'), ('1min', '1min'), ('15min', '15min'), ('30min', '30min'), ('60min', '60min'), ('1d', '1d')], max_length=5),
        ),
    ]
