# Generated by Django 3.0.6 on 2020-06-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20200629_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('quote', 'quote'), ('1min', '1min'), ('15min', '15min'), ('30min', '30min'), ('60min', '60min'), ('1d', '1d')], db_index=True, max_length=5),
        ),
    ]
