# Generated by Django 3.0.6 on 2020-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_auto_20200629_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='exchange_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
