# Generated by Django 3.0.6 on 2020-08-27 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(max_length=64)),
                ('starting_year', models.IntegerField(default=2010)),
                ('end_year', models.IntegerField(default=2020)),
                ('agent_starting_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('time_elapsed', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='simulation.Simulation')),
                ('risk_affinity', models.SmallIntegerField()),
                ('diversification', models.SmallIntegerField()),
                ('placeholder', models.SmallIntegerField()),
            ],
        ),
    ]
