# Generated by Django 3.0.6 on 2020-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateField(),
        ),
    ]
