# Generated by Django 3.0.6 on 2020-08-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_auto_20200829_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='agent_cash_left',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
