# Generated by Django 3.0.6 on 2020-09-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_simulation_agent_end_portfolio_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(blank=True, default=0, max_length=1024, null=True),
        ),
    ]
